names:
- text
- junction
- crossover
- terminal
- gnd
- vss
- voltage.dc
- voltage.ac
- voltage.battery
- resistor
- resistor.adjustable
- resistor.photo
- capacitor.unpolarized
- capacitor.polarized
- capacitor.adjustable
- inductor
- inductor.ferrite
- inductor.coupled
- transformer
- diode
- diode.light_emitting
- diode.thyrector
- diode.zener
- diac
- triac
- thyristor
- varistor
- transistor.bjt
- transistor.fet
- transistor.photo
- operational_amplifier
- operational_amplifier.schmitt_trigger
- optocoupler
- integrated_circuit
- integrated_circuit.ne555
- integrated_circuit.voltage_regulator
- xor
- and
- or
- not
- nand
- nor
- probe
- probe.current
- probe.voltage
- switch
- relay
- socket
- fuse
- speaker
- motor
- lamp
- microphone
- antenna
- crystal
- mechanical
- magnetic
- optical
nc: 58
test: /root/autodl-fs/yolo_component_dataset/test/images
train: /root/autodl-fs/yolo_component_dataset/train/images
val: /root/autodl-fs/yolo_component_dataset/valid/images
